// Productos reales de Inversiones en Salud - Coosalud Inversa S.A.
// initialStock = stock actual del último control
// dailyRate = consumo diario histórico
// PRODUCT_ORDER debe coincidir con el orden de filas 3-30 en el Excel corporativo
export const PRODUCTS = [
  {
    id: 'ambientador',
    name: 'Ambientador Glade Aerosol',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['ambientador', 'glade', 'aerosol'],
    initialStock: 6,
    dailyRate: 0.1111,
  },
  {
    id: 'aromatica_manz',
    name: 'Aromática Bamby Manzanilla',
    unit: 'CAJA',
    category: 'cafeteria',
    keywords: ['aromatica', 'manzanilla', 'bamby', 'aromática'],
    initialStock: 4,
    dailyRate: 0.1667,
  },
  {
    id: 'aromatica_yerba',
    name: 'Aromática Bamby Yerbabuena',
    unit: 'CAJA',
    category: 'cafeteria',
    keywords: ['aromatica', 'yerbabuena', 'yerba', 'aromática'],
    initialStock: 4,
    dailyRate: 0.1667,
  },
  {
    id: 'aromatica_frutos',
    name: 'Aromática Frutos Rojos',
    unit: 'CAJA',
    category: 'cafeteria',
    keywords: ['aromatica', 'frutos', 'rojos', 'aromática', 'roja'],
    initialStock: 4,
    dailyRate: 0.1667,
  },
  {
    id: 'bolsas_negras',
    name: 'Bolsas Basura Negras x10',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['bolsa', 'basura', 'negra', 'bolsas', 'negras'],
    initialStock: 30,
    dailyRate: 2.0,
  },
  {
    id: 'bolsa_canequer',
    name: 'Bolsa Canequer Verde x50',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['canequer', 'verde', 'canequera', 'bolsa canequer'],
    initialStock: 1.92,
    dailyRate: 0.0333,
  },
  {
    id: 'cafe',
    name: 'Café Sello Rojo x500gr',
    unit: 'BOLSA',
    category: 'cafeteria',
    keywords: ['cafe', 'café', 'sello', 'rojo', 'coffee', 'tinto'],
    initialStock: 12,
    dailyRate: 1.0,
  },
  {
    id: 'desinfectante',
    name: 'Desinfectante Limpiapiso x5L',
    unit: 'GALON',
    category: 'aseo',
    keywords: ['desinfectante', 'limpiapiso', 'relajante', 'desinfect'],
    initialStock: 3,
    dailyRate: 0.1667,
  },
  {
    id: 'desmanchador',
    name: 'Desmanchador Baños 950cc',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['desmanchador', 'baños', 'baño', 'desmancha'],
    initialStock: 1,
    dailyRate: 0.0333,
  },
  {
    id: 'detergente',
    name: 'Detergente Multi Neutro x1kg',
    unit: 'BOLSA',
    category: 'aseo',
    keywords: ['detergente', 'neutro', 'multi', 'deterge'],
    initialStock: 4,
    dailyRate: 0.2,
  },
  {
    id: 'esponja_acero',
    name: 'Esponja de Acero (Brillo)',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['esponja acero', 'brillo', 'acero'],
    initialStock: 11,
    dailyRate: 0,
  },
  {
    id: 'jabon',
    name: 'Jabón Líquido Manos x4L',
    unit: 'GALON',
    category: 'aseo',
    keywords: ['jabon', 'jabón', 'liquido', 'manos', 'jabón manos'],
    initialStock: 3,
    dailyRate: 0.1667,
  },
  {
    id: 'lavaloza_800',
    name: 'Lavaloza Crema Axion x800g',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['lavaloza', 'axion', 'lava', 'loza', 'lavaplatos'],
    initialStock: 4,
    dailyRate: 0.25,
  },
  {
    id: 'lavaloza_450',
    name: 'Lavaloza Crema Axion x450g',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['lavaloza 450', 'axion 450', '450'],
    initialStock: 1,
    dailyRate: 0.25,
  },
  {
    id: 'pano',
    name: 'Paño Micro Vidrios',
    unit: '10 UNID',
    category: 'aseo',
    keywords: ['paño', 'pano', 'micro', 'vidrio', 'azul', 'microfibra'],
    initialStock: 0.83,
    dailyRate: 0.3333,
  },
  {
    id: 'papel',
    name: 'Papel Higiénico Jumbo 8x170m',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['papel', 'higienico', 'jumbo', 'pap', 'sanitario', 'papel higiénico', 'pap.hig'],
    initialStock: 44,
    dailyRate: 3.0,
  },
  {
    id: 'raid',
    name: 'Raid Mata Cucaracha 300g',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['raid', 'cucaracha', 'insecticida', 'mata'],
    initialStock: 2,
    dailyRate: 0.1429,
  },
  {
    id: 'azucar',
    name: 'Azúcar Manuelita x200 Sobres',
    unit: 'CAJA',
    category: 'cafeteria',
    keywords: ['azucar', 'azúcar', 'manuelita', 'sobres', 'sugar'],
    initialStock: 2,
    dailyRate: 0.1429,
  },
  {
    id: 'toalla',
    name: 'Toalla Precortada 6x100m',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['toalla', 'precortada', 'toal', 'fmax', 'papel manos'],
    initialStock: 21,
    dailyRate: 2.0,
  },
  {
    id: 'trapero',
    name: 'Repuesto de Trapero',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['trapero', 'repuesto', 'trapeador', 'mopa'],
    initialStock: 2,
    dailyRate: 0.1429,
  },
  {
    id: 'guantes_nitrilo',
    name: 'Guantes De Nitrilo x50',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['guante nitrilo', 'nitrilo', 'nitrile', 'guantes nitrilo'],
    initialStock: 2,
    dailyRate: 0.1111,
  },
  {
    id: 'tapabocas',
    name: 'Tapabocas x50',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['tapabocas', 'mascarilla', 'tapa', 'tapaboca'],
    initialStock: 2.22,
    dailyRate: 0.1429,
  },
  {
    id: 'limpiavidrios',
    name: 'Limpia Vidrios Galón',
    unit: 'GALON',
    category: 'aseo',
    keywords: ['limpiavidrios', 'limpia vidrios', 'vidrios', 'ventanas'],
    initialStock: 0,
    dailyRate: 0.0333,
  },
  {
    id: 'cloro',
    name: 'Cloro',
    unit: 'GALON',
    category: 'aseo',
    keywords: ['cloro', 'blanqueador', 'hipoclorito', 'lejia'],
    initialStock: 2,
    dailyRate: 0.1429,
  },
  {
    id: 'varsol',
    name: 'Varsol Ecológico 1000cc',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['varsol', 'ecologico', 'fuller'],
    initialStock: 0,
    dailyRate: 0.0333,
  },
  {
    id: 'esponjas12',
    name: 'Esponjas x12',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['esponja x12', 'esponjas x12', 'esponjas 12'],
    initialStock: 0.25,
    dailyRate: 0,
  },
  {
    id: 'esponjas18',
    name: 'Esponjas x18',
    unit: 'PAQUETES',
    category: 'aseo',
    keywords: ['esponja x18', 'esponjas x18', 'esponjas 18', 'esponja'],
    initialStock: 0.72,
    dailyRate: 0.0139,
  },
  {
    id: 'guantes_manga',
    name: 'Guantes Media Manga',
    unit: 'UNIDAD',
    category: 'aseo',
    keywords: ['guante manga', 'manga', 'media manga', 'guantes manga'],
    initialStock: 2,
    dailyRate: 0.0667,
  },
]

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map(p => [p.id, p]))

// Order must match rows 3-30 in "Matriz de Consumo (2)" sheet
export const PRODUCT_ORDER = PRODUCTS.map(p => p.id)
