// 28 products — update initialStock and dailyRate with real data from the May 2026 inventory file.
// PRODUCT_ORDER must match the row order in "Matriz de Consumo (2)" rows 3-30.
export const PRODUCTS = [
  // ── CAFETERÍA ────────────────────────────────────────────────────────────
  {
    id: 'cafe',
    name: 'Café (Tinto)',
    unit: 'libra',
    category: 'cafeteria',
    keywords: ['cafe', 'café', 'tinto', 'cafetito', 'cafecito'],
    initialStock: 5,
    dailyRate: 0.33,
  },
  {
    id: 'azucar',
    name: 'Azúcar',
    unit: 'libra',
    category: 'cafeteria',
    keywords: ['azucar', 'azúcar', 'azucarera'],
    initialStock: 8,
    dailyRate: 0.5,
  },
  {
    id: 'panela',
    name: 'Panela',
    unit: 'unidad',
    category: 'cafeteria',
    keywords: ['panela', 'panelita'],
    initialStock: 6,
    dailyRate: 0.25,
  },
  {
    id: 'vasos',
    name: 'Vasos Desechables',
    unit: 'paquete',
    category: 'cafeteria',
    keywords: ['vasos', 'vaso', 'desechable', 'desechables', 'vasito'],
    initialStock: 10,
    dailyRate: 1,
  },
  {
    id: 'platos',
    name: 'Platos Desechables',
    unit: 'paquete',
    category: 'cafeteria',
    keywords: ['platos', 'plato', 'platico'],
    initialStock: 8,
    dailyRate: 0.5,
  },
  {
    id: 'cucharas',
    name: 'Cucharas Plásticas',
    unit: 'paquete',
    category: 'cafeteria',
    keywords: ['cucharas', 'cuchara', 'cucharita', 'cucharitas'],
    initialStock: 10,
    dailyRate: 0.5,
  },
  {
    id: 'servilletas',
    name: 'Servilletas',
    unit: 'paquete',
    category: 'cafeteria',
    keywords: ['servilletas', 'servilleta', 'servill'],
    initialStock: 12,
    dailyRate: 1,
  },
  {
    id: 'agua',
    name: 'Agua (Botellón)',
    unit: 'botellón',
    category: 'cafeteria',
    keywords: ['agua', 'botellon', 'botellón', 'aguita'],
    initialStock: 4,
    dailyRate: 0.5,
  },
  {
    id: 'aromaticas',
    name: 'Aromáticas',
    unit: 'caja',
    category: 'cafeteria',
    keywords: ['aromaticas', 'aromáticas', 'aromatica', 'aromática', 'te', 'té'],
    initialStock: 3,
    dailyRate: 0.2,
  },
  {
    id: 'palillos',
    name: 'Palillos',
    unit: 'caja',
    category: 'cafeteria',
    keywords: ['palillos', 'palillo', 'mondadientes'],
    initialStock: 5,
    dailyRate: 0.1,
  },
  {
    id: 'pitillos',
    name: 'Pitillos',
    unit: 'paquete',
    category: 'cafeteria',
    keywords: ['pitillos', 'pitillo', 'sorbeto', 'sorbetos', 'pajilla'],
    initialStock: 6,
    dailyRate: 0.2,
  },
  {
    id: 'papel_aluminio',
    name: 'Papel Aluminio',
    unit: 'rollo',
    category: 'cafeteria',
    keywords: ['papel aluminio', 'aluminio', 'papel_aluminio'],
    initialStock: 3,
    dailyRate: 0.15,
  },
  // ── ASEO ─────────────────────────────────────────────────────────────────
  {
    id: 'papel_hig',
    name: 'Papel Higiénico',
    unit: 'paquete',
    category: 'aseo',
    keywords: ['papel', 'papel higienico', 'papel higiénico', 'pap.hig', 'papeles', 'higienico'],
    initialStock: 20,
    dailyRate: 2,
  },
  {
    id: 'jabon_manos',
    name: 'Jabón Líquido Manos',
    unit: 'litro',
    category: 'aseo',
    keywords: ['jabon', 'jabón', 'jabon manos', 'jabón manos', 'jabon liquido', 'jabonera'],
    initialStock: 4,
    dailyRate: 0.3,
  },
  {
    id: 'desinfectante',
    name: 'Desinfectante',
    unit: 'litro',
    category: 'aseo',
    keywords: ['desinfectante', 'desinfect'],
    initialStock: 5,
    dailyRate: 0.4,
  },
  {
    id: 'escoba',
    name: 'Escoba',
    unit: 'unidad',
    category: 'aseo',
    keywords: ['escoba', 'escobas', 'escobilla'],
    initialStock: 3,
    dailyRate: 0.05,
  },
  {
    id: 'trapero',
    name: 'Trapero',
    unit: 'unidad',
    category: 'aseo',
    keywords: ['trapero', 'traperos', 'trapeador', 'mopa', 'mopas'],
    initialStock: 3,
    dailyRate: 0.05,
  },
  {
    id: 'bolsas_grandes',
    name: 'Bolsas Basura Grandes',
    unit: 'paquete',
    category: 'aseo',
    keywords: ['bolsas grandes', 'bolsa grande', 'bolsas basura', 'bolsa basura'],
    initialStock: 8,
    dailyRate: 0.5,
  },
  {
    id: 'bolsas_medianas',
    name: 'Bolsas Medianas',
    unit: 'paquete',
    category: 'aseo',
    keywords: ['bolsas medianas', 'bolsa mediana', 'bolsitas', 'bolsas'],
    initialStock: 6,
    dailyRate: 0.3,
  },
  {
    id: 'detergente',
    name: 'Detergente',
    unit: 'kilo',
    category: 'aseo',
    keywords: ['detergente', 'deterge', 'lavaplatos', 'lava'],
    initialStock: 5,
    dailyRate: 0.25,
  },
  {
    id: 'limpiador',
    name: 'Limpiador Multiusos',
    unit: 'litro',
    category: 'aseo',
    keywords: ['limpiador', 'multiusos', 'limpiamuebles', 'fabuloso', 'ajax'],
    initialStock: 4,
    dailyRate: 0.2,
  },
  {
    id: 'alcohol',
    name: 'Alcohol Antiséptico',
    unit: 'litro',
    category: 'aseo',
    keywords: ['alcohol', 'antiseptico', 'antiséptico', 'gel'],
    initialStock: 6,
    dailyRate: 0.4,
  },
  {
    id: 'guantes',
    name: 'Guantes de Caucho',
    unit: 'par',
    category: 'aseo',
    keywords: ['guantes', 'guante', 'caucho'],
    initialStock: 4,
    dailyRate: 0.1,
  },
  {
    id: 'estropajo',
    name: 'Estropajo / Esponja',
    unit: 'unidad',
    category: 'aseo',
    keywords: ['estropajo', 'esponja', 'estropajos', 'esponjas', 'fibra'],
    initialStock: 5,
    dailyRate: 0.2,
  },
  {
    id: 'limpiavidrios',
    name: 'Limpiavidrios',
    unit: 'litro',
    category: 'aseo',
    keywords: ['limpiavidrios', 'vidrios', 'ventanas', 'windex'],
    initialStock: 2,
    dailyRate: 0.1,
  },
  {
    id: 'ambientador',
    name: 'Ambientador',
    unit: 'unidad',
    category: 'aseo',
    keywords: ['ambientador', 'aromatizante', 'glade', 'ambiente'],
    initialStock: 4,
    dailyRate: 0.15,
  },
  {
    id: 'hipoclorito',
    name: 'Hipoclorito',
    unit: 'litro',
    category: 'aseo',
    keywords: ['hipoclorito', 'cloro', 'blanqueador', 'lejia', 'lejía'],
    initialStock: 5,
    dailyRate: 0.3,
  },
  {
    id: 'cera_pisos',
    name: 'Cera para Pisos',
    unit: 'litro',
    category: 'aseo',
    keywords: ['cera', 'cera pisos', 'brillo pisos', 'brillador'],
    initialStock: 3,
    dailyRate: 0.1,
  },
]

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map(p => [p.id, p]))

// Order must match row order in "Matriz de Consumo (2)" rows 3-30
export const PRODUCT_ORDER = PRODUCTS.map(p => p.id)
